version: "3.8"
services:

  redis_admin:
    image: redis
    ports:
      - "7084:7084"
    restart: always
    networks:
      - app_network
    volumes:
      - redis_admin_volume:/DB/Redis/admin/data/db
    command: [ "redis-server", "--port", "7084" ]

  insight_telegram_admin:
    image: docker.io/artemprod/insighter_bot_admin:${IMAGE_TAG:-latest}
    restart: always
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - redis_admin



volumes:
  redis_admin_volume:

networks:
  app_network:
    external: true